import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Cart() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Store Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <p>cart stuff</p>
      </main>
    </div>
  )
}
