import Head from 'next/head';
import {CartContext} from '../Context/CartContext';
import LiveCart from "../Comps/LiveCart"
import styles from '../styles/Home.module.css';

export default function Cart() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Store Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <CartContext.Consumer>
            {(context)=> {
              return(
                <LiveCart client={context.client} cartId={context.cartId} lineItems ={context.lineItems}/>
              )
            }}
      </CartContext.Consumer>
      </main>
    </div>
  )
}
