import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState} from "react"
import {ShopifyClientContext} from "../Context/ShopifyClientContext";
import LiveShop from '../Comps/LiveShop';


export default function Shop() {
    const [finder,setFinder] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Store Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <ShopifyClientContext.Consumer>
            {(context) => {
              return(
                <LiveShop store={context.store}  sortBy={context.sortBy}/>
              )
            }}
      </ShopifyClientContext.Consumer>
      </main>
    </div>
  )
}
